'use client';
import { useEffect, useRef, useState } from 'react';
import maplibregl from 'maplibre-gl';
import { LocateFixed, MapPin, RotateCcw } from 'lucide-react';
import { stands, stopNumber, type TourState } from '../lib/data';
const tourBounds = () => stands.reduce((bounds, stand) => bounds.extend(stand.coords), new maplibregl.LngLatBounds());
export default function TourMap({selected,state,onSelect}:{selected:string;state:TourState;onSelect:(id:string)=>void}) {
 const host=useRef<HTMLDivElement>(null),map=useRef<maplibregl.Map|null>(null),markers=useRef<maplibregl.Marker[]>([]),select=useRef(onSelect),locationMarker=useRef<maplibregl.Marker|null>(null);
 const [failed,setFailed]=useState(false),[loaded,setLoaded]=useState(false),[locationNote,setLocationNote]=useState(''),[locating,setLocating]=useState(false);
 select.current=onSelect;
 useEffect(()=>{if(!host.current)return;let m:maplibregl.Map;let timer:ReturnType<typeof setTimeout>;try{m=new maplibregl.Map({container:host.current,style:'https://tiles.openfreemap.org/styles/positron',center:stands[0].coords,zoom:16.7,attributionControl:{compact:true},pitch:0});map.current=m;m.scrollZoom.disable();timer=setTimeout(()=>{if(!m.loaded())setFailed(true)},18000);m.on('load',()=>{clearTimeout(timer);setLoaded(true);setFailed(false);for(const layer of m.getStyle().layers){if(layer.type==='background')m.setPaintProperty(layer.id,'background-color','#f3eee4');if(layer.type==='fill'&&/park|landcover|landuse/.test(layer.id))m.setPaintProperty(layer.id,'fill-color','#dde4d4');}stands.forEach(s=>{const button=document.createElement('button');button.className='map-marker';button.textContent=stopNumber(s.id);button.setAttribute('aria-label',`${s.name} auf Karte auswählen`);button.onclick=()=>select.current(s.id);const marker=new maplibregl.Marker({element:button,anchor:'center'}).setLngLat(s.coords).addTo(m);markers.current.push(marker)});});m.on('error',()=>{if(!m.isStyleLoaded())setFailed(true)});}catch{setFailed(true)}return()=>{clearTimeout(timer);markers.current.forEach(x=>x.remove());markers.current=[];map.current?.remove();map.current=null}},[]);
 useEffect(()=>{markers.current.forEach((marker,i)=>{const el=marker.getElement();el.classList.toggle('selected',stands[i].id===selected);el.classList.toggle('visited',!!state.ratings[stands[i].id]);el.setAttribute('aria-pressed',String(stands[i].id===selected))});},[selected,state,loaded]);
 useEffect(()=>{const stop=stands.find(s=>s.id===selected);if(loaded&&stop)map.current?.easeTo({center:stop.coords,zoom:16.7,duration:matchMedia('(prefers-reduced-motion: reduce)').matches?0:450})},[selected,loaded]);
 function locate(){if(!navigator.geolocation){setLocationNote('Standort ist hier nicht verfügbar. Alle Stopps bleiben auf der Karte.');return}setLocating(true);navigator.geolocation.getCurrentPosition(p=>{setLocating(false);setLocationNote('Dein Standort wird nur auf diesem Gerät angezeigt.');if(!map.current)return;locationMarker.current?.remove();locationMarker.current=new maplibregl.Marker({color:'#407864'}).setLngLat([p.coords.longitude,p.coords.latitude]).addTo(map.current);map.current.easeTo({center:[p.coords.longitude,p.coords.latitude],zoom:15})},()=>{setLocating(false);setLocationNote('Standort nicht verfügbar. Wähle deinen nächsten Stopp direkt auf der Karte.')},{timeout:10000})}
 return <div className="map-wrap"><div ref={host} className="map" aria-label="Interaktive Karte der Weihnachtsmarkt-Stopps aus 2025 in Bielefeld"/><div className="map-label"><span className="live-dot"/> Bielefeld, Innenstadt</div>{!loaded&&!failed&&<div className="map-loading">Deine Tourkarte wird geladen …</div>}{failed&&<div className="map-fallback"><MapPin/><strong>Karte gerade nicht verfügbar</strong><p>Deine Stopps findest du in der Liste darunter.</p></div>}<div className="map-tools"><button aria-label="Meinen Standort anzeigen" disabled={locating||failed} onClick={locate}><LocateFixed size={19}/></button><button aria-label="Alle Tourstopps anzeigen" disabled={failed} onClick={()=>map.current?.fitBounds(tourBounds(),{padding:{top:28,bottom:45,left:30,right:30},maxZoom:15,duration:0})}><RotateCcw size={18}/></button></div><div className="map-legend"><span><i className="gold"/>Ausgewählt</span><span><i className="green"/>Bewertet</span><span><i/>Offen</span></div>{locationNote&&<p className="location-note" role="status">{locationNote}</p>}</div>
}
