'use client';
import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
export default function WinterCup({variant='cranberry'}:{variant?:'cranberry'|'atlas'}){
 const host=useRef<HTMLDivElement>(null),turn=useRef<(()=>void)|null>(null),[available,setAvailable]=useState(false);
 useEffect(()=>{if(!host.current)return;let renderer:THREE.WebGLRenderer;let raf=0,disposed=false;const scene=new THREE.Scene();const target=host.current;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});}catch{return}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(230,260,false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=variant==='atlas'?1.1:1.25;target.appendChild(renderer.domElement);setAvailable(true);
 const camera=new THREE.PerspectiveCamera(34,230/260,.1,50);camera.position.set(0,2.5,7.4);camera.lookAt(0,.2,0);
 scene.add(new THREE.HemisphereLight(0xfff4e5,0xc1a3ae,2.8));const key=new THREE.DirectionalLight(0xffeed5,5);key.position.set(-3,5,5);scene.add(key);const fill=new THREE.DirectionalLight(0xffffff,3);fill.position.set(4,1,3);scene.add(fill);const rimLight=new THREE.DirectionalLight(0xffcfc0,4);rimLight.position.set(-1,4,-3);scene.add(rimLight);
 const mug=new THREE.Group();scene.add(mug);mug.rotation.set(.05,-.32,-.14);
 const ceramic=new THREE.MeshPhysicalMaterial({color:variant==='atlas'?0x692a3e:0x941d37,roughness:variant==='atlas'?.24:.19,metalness:.05,clearcoat:1,clearcoatRoughness:.12});
 const profile=[new THREE.Vector2(0,-.78),new THREE.Vector2(.57,-.78),new THREE.Vector2(.67,-.72),new THREE.Vector2(.73,-.58),new THREE.Vector2(.79,.57),new THREE.Vector2(.80,.72),new THREE.Vector2(.79,.77),new THREE.Vector2(.735,.77),new THREE.Vector2(.73,.67),new THREE.Vector2(.67,-.57),new THREE.Vector2(0,-.62)];
 const cup=new THREE.Mesh(new THREE.LatheGeometry(profile,80),ceramic);mug.add(cup);
 const handleCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(.74,.53,0),new THREE.Vector3(1.23,.5,0),new THREE.Vector3(1.43,.12,0),new THREE.Vector3(1.27,-.36,0),new THREE.Vector3(.74,-.44,0)]);mug.add(new THREE.Mesh(new THREE.TubeGeometry(handleCurve,60,.11,16,false),ceramic));
 const gold=new THREE.MeshStandardMaterial({color:0xe6c491,metalness:.65,roughness:.23});const lip=new THREE.Mesh(new THREE.TorusGeometry(.768,.017,12,80),gold);lip.rotation.x=Math.PI/2;lip.position.y=.768;mug.add(lip);
 const liquid=new THREE.Mesh(new THREE.CircleGeometry(.721,64),new THREE.MeshPhysicalMaterial({color:0x391021,roughness:.18,metalness:.2,clearcoat:1}));liquid.rotation.x=-Math.PI/2;liquid.position.y=.647;mug.add(liquid);
 const labelCanvas=document.createElement('canvas');labelCanvas.width=512;labelCanvas.height=512;const ctx=labelCanvas.getContext('2d')!;ctx.fillStyle='#fff5e7';ctx.textAlign='center';ctx.font='600 32px Arial';ctx.fillText('GLÜHWEIN',256,160);ctx.font='700 170px Arial';ctx.fillText('26',256,327);ctx.font='500 27px Arial';ctx.fillText('B I E L E F E L D',256,385);ctx.lineWidth=3;ctx.strokeStyle='#fff5e7';ctx.beginPath();ctx.moveTo(133,420);ctx.lineTo(379,420);ctx.stroke();const labelTexture=new THREE.CanvasTexture(labelCanvas);labelTexture.colorSpace=THREE.SRGBColorSpace;const label=new THREE.Mesh(new THREE.CylinderGeometry(.801,.75,1.10,64,1,true,-.73,1.46),new THREE.MeshStandardMaterial({map:labelTexture,transparent:true,roughness:.3,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2}));label.position.y=.04;mug.add(label);
 const shape=new THREE.Shape();for(let i=0;i<10;i++){const angle=Math.PI/2+i*Math.PI/5,r=i%2===0?.19:.085;const x=Math.cos(angle)*r,y=Math.sin(angle)*r;if(i===0)shape.moveTo(x,y);else shape.lineTo(x,y)}shape.closePath();const charm=new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth:.035,bevelEnabled:true,bevelSegments:2,steps:1,bevelSize:.015,bevelThickness:.015}),gold);charm.position.set(1.18,-.38,.1);charm.rotation.z=-.2;mug.add(charm);const loop=new THREE.Mesh(new THREE.TorusGeometry(.08,.015,8,28),gold);loop.position.set(1.18,-.17,.08);mug.add(loop);
 const orange=new THREE.Mesh(new THREE.CircleGeometry(.19,32),new THREE.MeshStandardMaterial({color:0xec9c45,roughness:.55}));orange.rotation.x=-Math.PI/2;orange.position.set(.30,.654,-.23);mug.add(orange);
 const cinnamon=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,.6,12),new THREE.MeshStandardMaterial({color:0x95593b,roughness:.8}));cinnamon.rotation.set(Math.PI/2,0,.35);cinnamon.position.set(-.16,.68,-.29);mug.add(cinnamon);
 const steam:THREE.Mesh[]=[];for(let j=0;j<3;j++){const points=[];for(let i=0;i<18;i++){const y=i/17;points.push(new THREE.Vector3(Math.sin(y*6+j)*.11+(j-1)*.17,.85+y*1.25,-.1))}const mesh=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),40,.009,6,false),new THREE.MeshBasicMaterial({color:0xcabec3,transparent:true,opacity:.25,depthWrite:false}));mug.add(mesh);steam.push(mesh)}
 const shadowCanvas=document.createElement('canvas');shadowCanvas.width=128;shadowCanvas.height=128;const sc=shadowCanvas.getContext('2d')!,gradient=sc.createRadialGradient(64,64,3,64,64,60);gradient.addColorStop(0,'rgba(81,34,46,.18)');gradient.addColorStop(1,'rgba(81,34,46,0)');sc.fillStyle=gradient;sc.fillRect(0,0,128,128);const shadow=new THREE.Mesh(new THREE.PlaneGeometry(3.8,1.3),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(shadowCanvas),transparent:true,depthWrite:false}));shadow.position.set(.08,-1.1,-.25);shadow.rotation.x=-Math.PI/2;scene.add(shadow);
 let rotation=0,last=0;turn.current=()=>{rotation+=Math.PI*2;if(reduced){mug.rotation.y+=.4;renderer.render(scene,camera)}else if(!raf)raf=requestAnimationFrame(frame)};
 function frame(time=0){raf=0;if(disposed)return;const dt=Math.min(.05,(time-last)/1000);last=time;const t=time/1000;if(!reduced){mug.rotation.y=-.32+Math.sin(t*.35)*.12+rotation;rotation*=Math.exp(-dt*2.8);mug.position.y=Math.sin(t*.75)*.025;steam.forEach((s,i)=>{s.rotation.y=Math.sin(t*.5+i)*.1;(s.material as THREE.MeshBasicMaterial).opacity=.17+Math.sin(t*.7+i)*.05});charm.rotation.z=-.2+Math.sin(t*.8)*.08;}renderer.render(scene,camera);if(!reduced&&!document.hidden)raf=requestAnimationFrame(frame)}
 let visible=true;const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible&&!document.hidden&&!raf)frame(performance.now());else if(!visible){cancelAnimationFrame(raf);raf=0}},{threshold:.05});observer.observe(target);const visibility=()=>{cancelAnimationFrame(raf);raf=0;if(!document.hidden&&visible)frame(performance.now())};document.addEventListener('visibilitychange',visibility);frame();
 return()=>{disposed=true;cancelAnimationFrame(raf);observer.disconnect();document.removeEventListener('visibilitychange',visibility);turn.current=null;scene.traverse(obj=>{const m=obj as THREE.Mesh;if(m.geometry)m.geometry.dispose();if(m.material){const mats=Array.isArray(m.material)?m.material:[m.material];mats.forEach(mat=>{(mat as THREE.MeshStandardMaterial).map?.dispose();mat.dispose()})}});renderer.dispose();renderer.domElement.remove()}
 },[variant]);
 return <button className="winter-cup" aria-label="3D-Glühweintasse drehen" onClick={()=>turn.current?.()}><div ref={host}/>{!available&&<img src="/images/wine.jpg" alt="Glühweintassen" className="cup-fallback"/>}</button>
}
