import { initialState, type TourState } from './data';
const DB='glueh26-design-v2';
function openDB(): Promise<IDBDatabase> { return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('tour');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('Speicher ist blockiert.'))}) }
export async function loadTour(): Promise<TourState> { const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction('tour','readonly'),r=tx.objectStore('tour').get('state');r.onsuccess=()=>resolve(r.result||initialState);r.onerror=()=>reject(r.error);tx.oncomplete=()=>db.close()}) }
export async function saveTour(state: TourState) { const db=await openDB();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('tour','readwrite');tx.objectStore('tour').put(state,'state');tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)};tx.onabort=()=>{db.close();reject(tx.error)}}) }
export async function preparePhoto(file: File) { if(!file.type.startsWith('image/'))throw Error('Bitte eine Bilddatei auswählen.');if(file.size>15*1024*1024)throw Error('Dein Foto darf höchstens 15 MB groß sein.');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,1600/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d')!.drawImage(img,0,0,canvas.width,canvas.height);return {id:typeof crypto.randomUUID==='function'?crypto.randomUUID():Array.from(crypto.getRandomValues(new Uint8Array(16)),n=>n.toString(16).padStart(2,'0')).join(''),name:file.name,src:canvas.toDataURL('image/jpeg',.82)}}catch{throw Error('Dieses Bildformat konnte nicht geöffnet werden. Bitte JPG, PNG oder WebP wählen.')}finally{URL.revokeObjectURL(url)} }
/** Beliebige Werte im selben IndexedDB-Speicher (z. B. Warteschlange und Cache der Gruppe). */
export async function kvGet<T>(key: string): Promise<T | undefined> { const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction('tour','readonly'),r=tx.objectStore('tour').get(key);r.onsuccess=()=>resolve(r.result as T|undefined);r.onerror=()=>reject(r.error);tx.oncomplete=()=>db.close()}) }
export async function kvSet(key: string, value: unknown) { const db=await openDB();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('tour','readwrite');tx.objectStore('tour').put(value,key);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)};tx.onabort=()=>{db.close();reject(tx.error)}}) }
